/*
 * This source file was generated by the Gradle 'init' task
 */
package com.arcanjo.portaria;

import com.arcanjo.portaria.view.JanelaPrincipal;

public class App {
    public static void main(String[] args) {
        new JanelaPrincipal();
    }
}
